name: Kubescape 

on:
  push:
    branches: [ junit ]
  pull_request:
    branches: [ junit ]
   
jobs:
  configuration-validation-job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18

      - name: Build kubescape
        run: go build -o ks
        
      - name: Scan files
        run: ./ks scan -t 0 -f junit -o results.xml .

      - name: Publish Test Results
        uses: mikepenz/action-junit-report@v2
        if: always()
        with:
          report_paths: "*.xml" 